---
# tasks file for roles/haproxy

- name: Update the packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install haproxy
  apt:
    name: "{{ item }}"
  with_items:
    - haproxy

- name: Enable HAProxy init script
  lineinfile:
    path: /etc/default/haproxy
    regexp: "ENABLED=0"
    line: "ENABLED=1"

- name: Copy the original haproxy config
  command: cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

- name: Haproxy configuration file
  template:
    src: templates/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Enable HAproxy logging
  lineinfile:
    path:  /etc/rsyslog.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "#$ModLoad imudp", 'line': "$ModLoad imudp"}
    - {'regexp': "#$UDPServerRun 514", 'line': "$UDPServerRun 514"}
  notify:
    - restart rsyslog
    - restart haproxy
